### ISSUE TITLE
Animated Splash Screen

### ISSUE THREAD

**Issue by Shobu95** [Shobu95/SewisticApp#1]
The App needs a good looking Splash screen, with animations would be a plus.

**Comment by Samdid** [comment]
I would like to work on this issue. Can you plz assign it to me?

**Comment by Shobu95** [comment]
Start working on it locally. I ll assign it to you in a few hours. Thanks for contributing.

**Comment by Shobu95** [comment]
Do register for Hacktoberfest fest too so you can win swags.

**Comment by Samdid** [comment]
> Do register for Hacktoberfest fest too so you can win swags.

Yeah

**Comment by Samdid** [comment]
Hey @Shobu95, I just have to add the animations to the existing splash screen, right? or do I have to create the new one?

**Comment by Shobu95** [comment]
Hello @Samdid , you just have to add animations to the existing splash screen for example moving or fading the logo, showing a progress widget. Also, you are free to apply more ideas if you want. 
Happy Hacking.

**Comment by Samdid** [comment]
Okay, thanks!!

**Comment by msramesh2k1** [comment]
Hey @Shobu95 Can I work on this issue , I Can make splash screen into more standarized level

**Comment by msramesh2k1** [comment]
> Hey @Shobu95 Can I work on this issue , I Can make splash screen into more standarized level

can you please assign me

**Comment by nish2447** [comment]
@Ashwith25  If you don't mind I am working already brother

**Comment by Ashwith25** [comment]
Oh, that's cool! Good luck 👍

**Comment by Shobu95** [comment]
The animation looks good but keeping a button on a splash screen is not a good UX. Try using the animation using some time dilation instead of a button click.
