### ISSUE TITLE
Add flutter-lints Dependency

### ISSUE THREAD

**Issue by Samdid** [Shobu95/SewisticApp#11]
We need to test our app using GitHub Actions. Github Actions help us to automate our software development workflows in the same place we store code and collaborate on pull requests and issues. The speed of Github Actions is good, and its pricing is better than that of Travis.

Linting is the process of analyzing a source code for any programming error, stylistic errors or any bug that can occur in the code. It is helpful, if you are working in a team, that way the whole team will follow some specific rules in the codebase. It's also helpful in identifying some common and uncommon mistakes that are made during coding like logical errors, unused variables etc.

This is the package i propose to use here,
https://pub.dev/packages/flutter_lints

**Comment by Shobu95** [comment]
@Samdid sure brother. give it a try. 

Happy Hacking. !!!1
