### ISSUE TITLE
UI Update

### ISSUE THREAD

**Issue by Nikhil27b** [Shobu95/SewisticApp#7]
Can I fixed or improve the app please for hacktober fest please assign me task

**Comment by Shobu95** [comment]
![image](https://user-images.githubusercontent.com/20271259/136047443-201fd2fa-6599-45a5-a174-ec516b5b4e48.png)

Sure brother. Update this home screen to the design of your choice. 
make sure to read the CONTRIBUTORS.md file for instructions on making you PRs.

Happy Hacking!!!!

**Comment by nish2447** [comment]
![new](https://user-images.githubusercontent.com/57082077/136966774-3fc451bd-0181-426a-b920-42151cb0c976.jpeg)

I have changed this brother

**Comment by Shobu95** [comment]
@nish2447 Yes change it to pink please and yes make separate PRs for both.

**Comment by nish2447** [comment]
Shall I create a new branch? other than develop 

If you are solving an issue, checkout your branch from 'develop' and name it in the following convention:
